#!/bin/bash

set -e

cp /etc/letsencrypt/live/switch.key/cert.pem /srv/tftp/switch.crt
openssl rsa -in /etc/letsencrypt/live/switch.key/privkey.pem -out /srv/tftp/switch.key
chmod 644 /srv/tftp/switch.key

expect -c '
set timeout 30

set switchcredentials [open "/home/pi/.switchcredentials" r]

gets $switchcredentials switchaddr

gets $switchcredentials switchuser

gets $switchcredentials switchpass

close $switchcredentials

set me [exec hostname -I]

spawn telnet $switchaddr

expect "User:"

send "$switchuser\r"

expect "Password:"

send "$switchpass\r"

expect "T1600G-28PS>"

send "enable\r"

expect "T1600G-28PS#"

send "configure\r"

expect "T1600G-28PS(config)#"

send "ip http secure-server download certificate switch.crt ip-address $me\r"

expect "T1600G-28PS(config)#"

send "ip http secure-server download key switch.key ip-address $me\r"

expect "T1600G-28PS(config)#"

send "end\r"

expect "T1600G-28PS#"

send "copy running-config startup-config\r"

expect "T1600G-28PS#"

send "exit\r"

expect "T1600G-28PS>"

send "exit\r"

exit
'

rm /srv/tftp/switch.crt
rm /srv/tftp/switch.key

