#!/bin/bash

set -e -o pipefail -o allexport

cp /etc/letsencrypt/live/switch.wearden.me/cert.pem /srv/tftp/switch.crt
openssl rsa -in /etc/letsencrypt/live/switch.wearden.me/privkey.pem -out /srv/tftp/switch.key
chmod 644 /srv/tftp/switch.key

source /home/pi/.switchcredentials

me=$(ip route get $(dig +short $switchaddr) | sed 's/^.*src \([^ ]*\).*$/\1/;q')

expect -c '
set timeout 30
spawn telnet $env(switchaddr)
expect "User:"
send "$env(switchuser)\r"
expect "Password:"
send "$env(switchpass)\r"
expect "T1600G-28PS>"
send "enable\r"
expect "T1600G-28PS#"
send "configure\r"
expect "T1600G-28PS(config)#"
send "ip http secure-server download key switch.key ip-address $env(me)\r"
expect "T1600G-28PS(config)#"
send "ip http secure-server download certificate switch.crt ip-address $env(me)\r"
expect "T1600G-28PS(config)#"
send "end\r"
expect "T1600G-28PS#"
send "copy running-config startup-config\r"
expect "T1600G-28PS#"
send "exit\r"
expect "T1600G-28PS>"
send "exit\r"
exit
'

rm /srv/tftp/switch.crt
rm /srv/tftp/switch.key
